//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoCReports.Templates.ReportTemplates {
    
    public partial class MasterDetailsRpt : DevExpress.XtraReports.UI.XtraReport {
        private void InitializeComponent() {
            DevExpress.XtraReports.ReportInitializer reportInitializer = new DevExpress.XtraReports.ReportInitializer(this, "PoCReports.Templates.ReportTemplates.MasterDetailsRpt.repx");

            // Controls
            this.TopMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.TopMarginBand>("TopMargin");
            this.BottomMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.BottomMarginBand>("BottomMargin");
            this.Detail = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("Detail");
            this.DetailReport = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailReportBand>("DetailReport");
            this.line2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLine>("line2");
            this.SupplierLabel = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("SupplierLabel");
            this.DetailReportDetail = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("DetailReportDetail");
            this.DetailReportInner = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailReportBand>("DetailReportInner");
            this.line1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLine>("line1");
            this.ProductLabel = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("ProductLabel");
            this.DetailReportInnerDetail = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("DetailReportInnerDetail");
            this.table1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table1");
            this.tableRow1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow1");
            this.tcProductQuantity = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tcProductQuantity");
            this.tcProductUnitPrice = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tcProductUnitPrice");
            this.tcProductPriceTotal = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tcProductPriceTotal");
            this.tableOfContents1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableOfContents>("tableOfContents1");
            this.ReportHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportHeaderBand>("ReportHeader");

            // Styles
            this.Style1 = reportInitializer.GetStyle("Style1");
        }
        private DevExpress.XtraReports.UI.TopMarginBand TopMargin;
        private DevExpress.XtraReports.UI.BottomMarginBand BottomMargin;
        private DevExpress.XtraReports.UI.DetailBand Detail;
        private DevExpress.XtraReports.UI.DetailReportBand DetailReport;
        private DevExpress.XtraReports.UI.XRLine line2;
        private DevExpress.XtraReports.UI.XRLabel SupplierLabel;
        private DevExpress.XtraReports.UI.DetailBand DetailReportDetail;
        private DevExpress.XtraReports.UI.DetailReportBand DetailReportInner;
        private DevExpress.XtraReports.UI.XRLine line1;
        private DevExpress.XtraReports.UI.XRLabel ProductLabel;
        private DevExpress.XtraReports.UI.DetailBand DetailReportInnerDetail;
        private DevExpress.XtraReports.UI.XRTable table1;
        private DevExpress.XtraReports.UI.XRTableRow tableRow1;
        private DevExpress.XtraReports.UI.XRTableCell tcProductQuantity;
        private DevExpress.XtraReports.UI.XRTableCell tcProductUnitPrice;
        private DevExpress.XtraReports.UI.XRTableCell tcProductPriceTotal;
        private DevExpress.XtraReports.UI.XRControlStyle Style1;
        private DevExpress.XtraReports.UI.XRTableOfContents tableOfContents1;
        private DevExpress.XtraReports.UI.ReportHeaderBand ReportHeader;
    }
}
